on:
  push:
    branches: [main, master]

name: build_report

jobs:
  build_report:
    runs-on: ${{ matrix.config.os }}

    name: ${{ matrix.config.os }} (${{ matrix.config.r }})

    strategy:
      fail-fast: false
      matrix:
        config:
          - {os: windows-latest, r: 'release'}

    env:
      R_REMOTES_NO_ERRORS_FROM_WARNINGS: true
      RSPM: ${{ matrix.config.rspm }}

    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: ${{ matrix.config.r }}

      - name: Install dependencies
        run: |
          #install.packages("drat")
          #drat::addRepo("hyenaproject")
          #install.packages("hyenaR")
          install.packages("remotes")
          remotes::install_github("hyenaproject/NgoroWeather/pkg", dependencies = TRUE)
        shell: Rscript {0}

      - name: Build pdf report
        run: |
          rmarkdown::render(input = "./report/markdown/NCAA_weather_report_pdf.Rmd", output_dir = "./report", output_file = "NCAA_weather_report.pdf")
        shell: Rscript {0}

      - name: check for changes
        run: git status

      - name: stage changed files
        run: git add .

      - name: commit changed files
        run: git commit -m "Auto updating report"

      - name: fetch from master
        run: git fetch origin master

      - name: push code to master
        run: git push origin HEAD:master
